.TH "s_col" 3 "Tue Jan 2 2018" "TCAT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_col \- Definition d'une structure de donnee permettant de stocker en memoire les colonnes issues d'une ligne isolee\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csv\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBcell\fP [COL_SIZE]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition d'une structure de donnee permettant de stocker en memoire les colonnes issues d'une ligne isolee\&. 
.SH "Field Documentation"
.PP 
.SS "char cell[COL_SIZE]"
Chaine de caractere permettant de stocker une cellule du fichier csv\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TCAT from the source code\&.
