.TH "s_lines" 3 "Tue Jan 2 2018" "TCAT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_lines \- Definition d'une structure de donnee permettant de stocker en memoire les lignes de bus\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <db\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "\fBllist\fP * \fBdirections\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition d'une structure de donnee permettant de stocker en memoire les lignes de bus\&. 
.SH "Field Documentation"
.PP 
.SS "\fBllist\fP* directions"
Pointeur sur le type llist\&. directions est une liste chainee des directions possibles pour une ligne\&. 
.SS "int num"
Entier permettant de stocker le numero d'une ligne 

.SH "Author"
.PP 
Generated automatically by Doxygen for TCAT from the source code\&.
