.TH "s_list" 3 "Tue Jan 2 2018" "TCAT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_list \- Definition d'une structure generique pour les listes chainees\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <llist\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "struct \fBs_list\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition d'une structure generique pour les listes chainees\&. 
.SH "Field Documentation"
.PP 
.SS "void* data"
Pointeur vers n'importe quel objet\&. Il peut notamment servir a pointer vers des structures specifiques a chaque liste\&. 
.SS "struct \fBs_list\fP* next"
Pointeur vers le prochain element de llist 

.SH "Author"
.PP 
Generated automatically by Doxygen for TCAT from the source code\&.
