.TH "s_row" 3 "Tue Jan 2 2018" "TCAT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_row \- Definition d'une structure de donnee permettant de stocker en memoire les lignes d'un fichier\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csv\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBllist\fP * \fBcol\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition d'une structure de donnee permettant de stocker en memoire les lignes d'un fichier\&. 
.SH "Field Documentation"
.PP 
.SS "\fBllist\fP* \fBcol\fP"
Pointeur sur le type llist\&. col est une liste chainee de colonnes\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TCAT from the source code\&.
