.TH "s_schedule" 3 "Tue Jan 2 2018" "TCAT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_schedule \- Definition d'une structure de donnee permettant de stocker en memoire les horaires d'un arret\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <db\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBtime\fP [6]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition d'une structure de donnee permettant de stocker en memoire les horaires d'un arret\&. 
.SH "Field Documentation"
.PP 
.SS "char time[6]"
Chaine de caractere permettant de stocker un horaire\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TCAT from the source code\&.
